'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'cs' | 'ru'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.containers': 'Containers',
    'nav.excavators': 'Excavators',
    'nav.constructions': 'Constructions',
    'nav.home': 'Select a section to explore our services',
    
    // Containers
    'containers.title': 'Containers',
    'containers.explore': 'Explore our container solutions',
    'containers.subtitle': 'Choose from our most popular container sizes. Designed to match your project needs and delivered quickly.',
    'containers.order': 'Order container',
    'containers.3m3.desc': 'Compact container suitable for light waste, wood, small rubble, soil and similar materials.',
    'containers.5m3.desc': 'Medium container ideal for general construction waste, renovation materials and bulk debris.',
    'containers.7m3.desc': 'Medium container ideal for general construction waste, renovation materials and bulk debris.',
    'containers.9m3.desc': 'Large container perfect for extensive cleanup, demolition projects and high-volume waste.',
    'containers.price': 'Price from',
    'containers.loading': 'Loading containers...',
    'containers.noAvailable': 'No containers available at the moment.',
    'containers.vat': 'excl. VAT',
    
    // Excavators
    'excavators.title': 'Excavators',
    'excavators.discover': 'Discover our excavator services',
    'excavators.subtitle': 'Professional excavators for all your construction and earthmoving needs. High-quality equipment with experienced operators available.',
    'excavators.order': 'Order excavator',
    'excavators.mini': 'Mini Excavator',
    'excavators.standard': 'Standard Excavator',
    'excavators.large': 'Large Excavator',
    'excavators.tb145.desc': 'Compact and versatile mini excavator perfect for tight spaces, landscaping, and small construction projects.',
    'excavators.tb157.desc': 'Compact mini excavator ideal for digging, trenching, and light demolition work in confined areas.',
    'excavators.tb260.desc': 'Mid-size excavator suitable for general construction, foundation work, and material handling.',
    'excavators.tb285.desc': 'Mid-size excavator with extended reach, perfect for deeper excavations and utility installations.',
    'excavators.tb2150.desc': 'Heavy-duty excavator designed for large-scale projects, quarrying, and major earthmoving operations.',
    'excavators.tb2150r.desc': 'Large demolition excavator with enhanced reach and power for demanding industrial applications.',
    'excavators.price.hour': 'hour',
    'excavators.loading': 'Loading excavators...',
    'excavators.noAvailable': 'No excavators available at the moment.',
    
    // Constructions
    'constructions.title': 'Constructions',
    'constructions.view': 'View our construction projects',
    'constructions.demolishing': 'Demolishing',
    'constructions.demolishing.desc': 'Professional demolition and dismantling services',
    'constructions.installations': 'Installations',
    'constructions.installations.desc': 'Professional installation services',
    'constructions.plumbing': 'Plumbing & Heating',
    'constructions.plumbing.desc': 'Expert plumbing and heating solutions',
    'constructions.order': 'Order construction',
    
    // Demolishing page
    'demolishing.title': 'Demolishing & Demolition Works',
    'demolishing.subtitle': 'Professional demolition services with modern equipment and experienced team',
    'demolishing.types': 'Types of Demolition',
    'demolishing.complete': 'Complete Demolition',
    'demolishing.complete.desc': 'Full building demolition including foundations',
    'demolishing.partial': 'Partial Demolition',
    'demolishing.partial.desc': 'Selective demolition of specific building parts',
    'demolishing.interior': 'Interior Demolition',
    'demolishing.interior.desc': 'Removal of interior structures and finishes',
    'demolishing.concrete': 'Concrete Demolition',
    'demolishing.concrete.desc': 'Breaking and removal of concrete structures',
    'demolishing.industrial': 'Industrial Demolition',
    'demolishing.industrial.desc': 'Dismantling of industrial facilities and equipment',
    'demolishing.emergency': 'Emergency Demolition',
    'demolishing.emergency.desc': '24/7 emergency demolition services',
    'demolishing.features': 'Our Features',
    'demolishing.safety': 'Safety First',
    'demolishing.safety.desc': 'Strict safety protocols and certified personnel',
    'demolishing.eco': 'Eco-Friendly',
    'demolishing.eco.desc': 'Waste sorting and recycling of materials',
    'demolishing.equipment': 'Modern Equipment',
    'demolishing.equipment.desc': 'Latest demolition machinery and tools',
    'demolishing.order': 'Request Demolition Quote',
    
    // Installations page
    'installations.title': 'Installations',
    'installations.subtitle': 'Professional installation services for your property',
    'installations.plumbing': 'Plumbing & Heating',
    'installations.plumbing.desc': 'Complete plumbing and heating installation services',
    'installations.order': 'Request Installation Quote',
    
    // Plumbing page
    'plumbing.title': 'Plumbing & Heating',
    'plumbing.coming': 'Coming Soon',
    'plumbing.desc': 'We are currently developing our plumbing and heating installation services.',
    'plumbing.check': 'Please check back soon for more information.',
    
    // Common
    'common.back': 'Back',
    'common.more': 'Learn More',
    
    // Order Form
    'order.title': 'Order Service',
    'order.firstName': 'First Name',
    'order.lastName': 'Last Name',
    'order.email': 'Email',
    'order.phone': 'Phone',
    'order.address': 'Service Address',
    'order.city': 'City',
    'order.zip': 'ZIP',
    'order.country': 'Country',
    'order.selectCountry': 'Select Country',
    'order.containerType': 'Container Type',
    'order.excavatorType': 'Excavator Type',
    'order.constructionType': 'Construction Type',
    'order.dateNeeded': 'Date Needed',
    'order.startTime': 'Start Time',
    'order.endTime': 'End Time',
    'order.additionalInfo': 'Additional Information (Optional)',
    'order.additionalInfoPlaceholder': 'Please provide any additional details about your order, special requirements, or delivery instructions...',
    'order.addressPlaceholder': 'Enter your full address',
    'order.endTimeError': '⚠ End time must be after start time',
    'order.cancel': 'Cancel',
    'order.submit': 'Submit Order',
    'order.submitting': 'Submitting...',
    'order.success': 'Order submitted successfully!',
    'order.successMessage': 'We\'ll contact you soon to discuss your requirements.',
    'order.error': 'Failed to submit order. Please try again.',
    
    // Admin
    'admin.login': 'admin',
    'admin.subtitle': 'Access your admin dashboard',
    'admin.password': 'admin',
    'admin.signIn': 'Sign In',
    'admin.signingIn': 'Signing in...',
    'admin.invalidPassword': 'Invalid password',
    'admin.backToWebsite': 'Back to Website',
    'admin.dashboard': 'Admin',
    'admin.orders': 'Orders',
    'admin.schedule': 'Schedule',
    'admin.logout': 'Logout',
    'admin.status': 'Status',
    'admin.total': 'Total',
    'admin.pending': 'Pending',
    'admin.inProgress': 'In Progress',
    'admin.completed': 'Completed',
    'admin.cancelled': 'Cancelled',
    'admin.updateStatus': 'Update Status',
    'admin.viewDetails': 'View Details',
    'admin.delete': 'Delete',
    'admin.noOrdersFound': 'No orders found with the selected filter.',
    'admin.loading': 'Loading...',
    'admin.error': 'Error',
    'admin.calendar': 'Calendar',
    'admin.connected': 'Connected',
    'admin.disconnected': 'Disconnected',
    'admin.scheduled': 'Scheduled',
    'admin.all': 'All',
    'admin.home': 'Home',
    'admin.newContainers': 'New Containers',
    'admin.newExcavators': 'New Excavators',
    'admin.workApplications': 'Work Applications',
    'admin.containerManagement': 'Container Management',
    'admin.containerManagementDesc': 'Manage containers displayed on the main website',
    'admin.excavatorManagement': 'Excavator Management',
    'admin.excavatorManagementDesc': 'Manage excavators displayed on the main website',
    'admin.workApplicationsTitle': 'Work Applications',
    'admin.workApplicationsDesc': 'Manage all form submissions from customers',
    
    // Admin form fields
    'admin.addNewContainer': 'Add New Container',
    'admin.addNewContainerDesc': 'Create a new container option',
    'admin.addNewExcavator': 'Add New Excavator',
    'admin.addNewExcavatorDesc': 'Create a new excavator option',
    'admin.loadingContainers': 'Loading containers...',
    'admin.loadingExcavators': 'Loading excavators...',
    'admin.visible': 'Visible',
    'admin.hidden': 'Hidden',
    'admin.hide': 'Hide',
    'admin.show': 'Show',
    'admin.edit': 'Edit',
    'admin.volume': 'Volume (m³)',
    'admin.price': 'Price (CZK)',
    'admin.dimensions': 'Dimensions (m)',
    'admin.description': 'Description',
    'admin.preset': 'Preset',
    'admin.custom': 'Custom',
    'admin.makeVisible': 'Make visible on website immediately',
    'admin.cancel': 'Cancel',
    'admin.adding': 'Adding...',
    'admin.addContainer': 'Add Container',
    'admin.addExcavator': 'Add Excavator',
    'admin.excavatorImage': 'Excavator Image',
    'admin.model': 'Model',
    'admin.type': 'Type',
    'admin.mini': 'Mini',
    'admin.standard': 'Standard',
    'admin.large': 'Large',
    'admin.specs': 'Specifications',
    'admin.weight': 'Weight',
    'admin.bucketCapacity': 'Bucket Capacity',
    'admin.maxReach': 'Max Reach',
    'admin.failedUpdateStatus': 'Failed to update container status',
    'admin.failedDelete': 'Failed to delete container',
    'admin.failedAdd': 'Failed to add container. Please try again.',
    'admin.fillAllDimensions': 'Please fill in all dimension fields (length, width, height)',
    'admin.confirmDelete': 'Are you sure you want to delete the {volume}m³ container?',
    'admin.confirmDeleteExcavator': 'Are you sure you want to delete the {model} excavator?',
    
    // Error messages
    'error.timeSlotBooked': 'This time slot is already booked. Please choose another time.',
    'error.failedOrder': 'Failed to create order',
    'error.failedBooking': 'Failed to process booking',
    'error.failedFetchSlots': 'Failed to fetch available slots',
    'error.failedUpdateStatus': 'Failed to update status',
    'error.failedDelete': 'Failed to delete',
    'error.failedAdd': 'Failed to add',
    'error.failedSave': 'Failed to save',
    'error.requiredFields': 'Please fill in all required fields',
    'error.somethingWrong': 'Something went wrong. Please try again.',
    
    // Container options
    'order.container.3m3': '3m³ Container (2 x 0.5 x 3.8 m)',
    'order.container.5m3': '5m³ Container (2 x 0.7 x 3.8 m)',
    
    // Excavator options
    'order.excavator.tb145': 'TB145 - Mini Excavator (1.5t, 0.04m³ bucket)',
    'order.excavator.tb290-1': 'TB290-1 - Compact Excavator (2.9t, 0.09m³ bucket)',
    'order.excavator.tb290-2': 'TB290-2 - Heavy Excavator (2.9t, 0.11m³ bucket)',
    
    // Construction options
    'order.construction.general': 'General Construction',
    'order.construction.earthworks': 'Earthworks',
    'order.construction.foundation': 'Foundation Work',
    'order.construction.demolition': 'Demolition',
    
    // Countries
    'order.country.czechRepublic': 'Czech Republic',
    'order.country.slovakia': 'Slovakia',
    'order.country.germany': 'Germany',
    'order.country.poland': 'Poland',
    'order.country.austria': 'Austria',
    
    // Work With Us
    'work.buttonText': 'Join Our Growing Team!',
    'work.formTitle': 'We\'re Hiring!',
    'work.subtitle': 'We are actively expanding our team and welcome talented professionals to grow with us',
    'work.firstName': 'First Name',
    'work.lastName': 'Last Name',
    'work.email': 'Email',
    'work.phone': 'Phone',
    'work.expertise': 'Your Expertise',
    'work.experience': 'Years of Experience',
    'work.message': 'Tell us about yourself',
    'work.submit': 'Send Application',
    'work.cancel': 'Cancel',
    'work.sending': 'Sending...',
    'work.success': 'Application sent successfully!',
    'work.error': 'Failed to send application. Please try again.',
    'work.expertise.demolition': 'Demolition',
    'work.expertise.construction': 'Construction',
    'work.expertise.operator': 'Equipment Operator',
    'work.expertise.safety': 'Safety Specialist',
    'work.expertise.management': 'Project Management',
    'work.expertise.other': 'Other',
    
    // Footer
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.socialInfo': 'Follow us on social media for the latest information',
    'footer.allRightsReserved': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
  },
  cs: {
    // Navigation
    'nav.containers': 'Kontejnery',
    'nav.excavators': 'Bagry',
    'nav.constructions': 'Stavby',
    'nav.home': 'Vyberte sekci pro prozkoumání našich služeb',
    
    // Containers
    'containers.title': 'Kontejnery',
    'containers.explore': 'Prozkoumejte naše kontejnerová řešení',
    'containers.subtitle': 'Vyberte si z našich nejoblíbenějších velikostí kontejnerů. Navrženo podle vašich potřeb a dodáno rychle.',
    'containers.order': 'Objednat kontejner',
    'containers.3m3.desc': 'Kompaktní kontejner vhodný pro lehký odpad, dřevo, drobnou suť, zeminu a podobné materiály.',
    'containers.5m3.desc': 'Střední kontejner ideální pro stavební odpad, renovační materiály a objemný odpad.',
    'containers.7m3.desc': 'Střední kontejner ideální pro stavební odpad, renovační materiály a objemný odpad.',
    'containers.9m3.desc': 'Velký kontejner perfektní pro rozsáhlý úklid, demoliční projekty a velkoobjemový odpad.',
    'containers.price': 'Cena od',
    'containers.loading': 'Načítání kontejnerů...',
    'containers.noAvailable': 'Momentálně nejsou k dispozici žádné kontejnery.',
    'containers.vat': 'bez DPH',
    
    // Excavators
    'excavators.title': 'Bagry',
    'excavators.discover': 'Objevte naše služby bagrů',
    'excavators.subtitle': 'Profesionální bagry pro všechny vaše stavební a zemní práce. Kvalitní vybavení se zkušenými operátory.',
    'excavators.order': 'Objednat bagr',
    'excavators.mini': 'Mini bagr',
    'excavators.standard': 'Standardní bagr',
    'excavators.large': 'Velký bagr',
    'excavators.tb145.desc': 'Kompaktní a všestranný mini bagr ideální pro stísněné prostory, terénní úpravy a malé stavební projekty.',
    'excavators.tb157.desc': 'Kompaktní mini bagr ideální pro kopání, výkopy a lehké demoliční práce ve stísněných prostorách.',
    'excavators.tb260.desc': 'Středně velký bagr vhodný pro obecné stavební práce, základové práce a manipulaci s materiálem.',
    'excavators.tb285.desc': 'Středně velký bagr s prodlouženým dosahem, ideální pro hlubší výkopy a instalace inženýrských sítí.',
    'excavators.tb2150.desc': 'Těžký bagr určený pro velké projekty, těžbu a rozsáhlé zemní práce.',
    'excavators.tb2150r.desc': 'Velký demoliční bagr se zvýšeným dosahem a výkonem pro náročné průmyslové aplikace.',
    'excavators.price.hour': 'hodina',
    'excavators.loading': 'Načítání bagrů...',
    'excavators.noAvailable': 'Momentálně nejsou k dispozici žádné bagry.',
    
    // Constructions
    'constructions.title': 'Stavby',
    'constructions.view': 'Zobrazit naše stavební projekty',
    'constructions.demolishing': 'Demolice',
    'constructions.demolishing.desc': 'Profesionální demoliční a bouracích práce',
    'constructions.installations': 'Instalace',
    'constructions.installations.desc': 'Profesionální instalační služby',
    'constructions.plumbing': 'Instalatérství a topení',
    'constructions.plumbing.desc': 'Odborné instalatérské a topné řešení',
    'constructions.order': 'Objednat stavbu',
    
    // Demolishing page
    'demolishing.title': 'Demolice a demoliční práce',
    'demolishing.subtitle': 'Profesionální demoliční služby s moderním vybavením a zkušeným týmem',
    'demolishing.types': 'Typy demolic',
    'demolishing.complete': 'Kompletní demolice',
    'demolishing.complete.desc': 'Úplná demolice budov včetně základů',
    'demolishing.partial': 'Částečná demolice',
    'demolishing.partial.desc': 'Selektivní demolice konkrétních částí budov',
    'demolishing.interior': 'Interiérová demolice',
    'demolishing.interior.desc': 'Odstranění vnitřních konstrukcí a povrchů',
    'demolishing.concrete': 'Demolice betonu',
    'demolishing.concrete.desc': 'Bourání a odstraňování betonových konstrukcí',
    'demolishing.industrial': 'Průmyslová demolice',
    'demolishing.industrial.desc': 'Demontáž průmyslových zařízení a vybavení',
    'demolishing.emergency': 'Havarijní demolice',
    'demolishing.emergency.desc': '24/7 havarijní demoliční služby',
    'demolishing.features': 'Naše výhody',
    'demolishing.safety': 'Bezpečnost na prvním místě',
    'demolishing.safety.desc': 'Přísné bezpečnostní protokoly a certifikovaný personál',
    'demolishing.eco': 'Ekologicky šetrné',
    'demolishing.eco.desc': 'Třídění odpadu a recyklace materiálů',
    'demolishing.equipment': 'Moderní vybavení',
    'demolishing.equipment.desc': 'Nejnovější demoliční stroje a nástroje',
    'demolishing.order': 'Požádat o cenovou nabídku demolice',
    
    // Installations page
    'installations.title': 'Instalace',
    'installations.subtitle': 'Profesionální instalační služby pro vaši nemovitost',
    'installations.plumbing': 'Instalatérství a topení',
    'installations.plumbing.desc': 'Kompletní instalatérské a topné služby',
    'installations.order': 'Požádat o cenovou nabídku instalace',
    
    // Plumbing page
    'plumbing.title': 'Instalatérství a topení',
    'plumbing.coming': 'Připravujeme',
    'plumbing.desc': 'Momentálně pracujeme na našich instalatérských a topných službách.',
    'plumbing.check': 'Brzy zde najdete více informací.',
    
    // Common
    'common.back': 'Zpět',
    'common.more': 'Zjistit více',
    
    // Order Form
    'order.title': 'Objednat službu',
    'order.firstName': 'Jméno',
    'order.lastName': 'Příjmení',
    'order.email': 'Email',
    'order.phone': 'Telefon',
    'order.address': 'Adresa služby',
    'order.city': 'Město',
    'order.zip': 'PSČ',
    'order.country': 'Země',
    'order.selectCountry': 'Vyberte zemi',
    'order.containerType': 'Typ kontejneru',
    'order.excavatorType': 'Typ bagru',
    'order.constructionType': 'Typ stavby',
    'order.dateNeeded': 'Požadované datum',
    'order.startTime': 'Čas začátku',
    'order.endTime': 'Čas konce',
    'order.additionalInfo': 'Dodatečné informace (volitelné)',
    'order.additionalInfoPlaceholder': 'Uveďte prosím jakékoli další podrobnosti o vaší objednávce, speciální požadavky nebo pokyny pro doručení...',
    'order.addressPlaceholder': 'Zadejte vaši úplnou adresu',
    'order.endTimeError': '⚠ Čas konce musí být po času začátku',
    'order.cancel': 'Zrušit',
    'order.submit': 'Odeslat objednávku',
    'order.submitting': 'Odesílání...',
    'order.success': 'Objednávka byla úspěšně odeslána!',
    'order.successMessage': 'Brzy vás kontaktujeme ohledně vašich požadavků.',
    'order.error': 'Nepodařilo se odeslat objednávku. Zkuste to prosím znovu.',
    
    // Admin
    'admin.login': 'admin',
    'admin.subtitle': 'Přístup k administrátorskému panelu',
    'admin.password': 'admin',
    'admin.signIn': 'Přihlásit se',
    'admin.signingIn': 'Přihlašování...',
    'admin.invalidPassword': 'Neplatné heslo',
    'admin.backToWebsite': 'Zpět na web',
    'admin.dashboard': 'admin',
    'admin.orders': 'Objednávky',
    'admin.schedule': 'Harmonogram',
    'admin.logout': 'Odhlásit se',
    'admin.status': 'Stav',
    'admin.total': 'Celkem',
    'admin.pending': 'Čeká',
    'admin.inProgress': 'V procesu',
    'admin.completed': 'Dokončeno',
    'admin.cancelled': 'Zrušeno',
    'admin.updateStatus': 'Aktualizovat stav',
    'admin.viewDetails': 'Zobrazit detaily',
    'admin.delete': 'Smazat',
    'admin.noOrdersFound': 'Nebyly nalezeny žádné objednávky s vybraným filtrem.',
    'admin.loading': 'Načítání...',
    'admin.error': 'Chyba',
    'admin.calendar': 'Kalendář',
    'admin.connected': 'Připojeno',
    'admin.disconnected': 'Odpojeno',
    'admin.scheduled': 'Naplánováno',
    'admin.all': 'Vše',
    'admin.home': 'Domů',
    'admin.newContainers': 'Nové kontejnery',
    'admin.newExcavators': 'Nové bagry',
    'admin.workApplications': 'Pracovní žádosti',
    'admin.containerManagement': 'Správa kontejnerů',
    'admin.containerManagementDesc': 'Spravujte kontejnery zobrazené na hlavní webové stránce',
    'admin.excavatorManagement': 'Správa bagrů',
    'admin.excavatorManagementDesc': 'Spravujte bagry zobrazené na hlavní webové stránce',
    'admin.workApplicationsTitle': 'Pracovní žádosti',
    'admin.workApplicationsDesc': 'Spravujte všechny formuláře odeslané zákazníky',
    
    // Admin form fields
    'admin.addNewContainer': 'Přidat nový kontejner',
    'admin.addNewContainerDesc': 'Vytvořit novou možnost kontejneru',
    'admin.addNewExcavator': 'Přidat nový bagr',
    'admin.addNewExcavatorDesc': 'Vytvořit novou možnost bagru',
    'admin.loadingContainers': 'Načítání kontejnerů...',
    'admin.loadingExcavators': 'Načítání bagrů...',
    'admin.visible': 'Viditelný',
    'admin.hidden': 'Skrytý',
    'admin.hide': 'Skrýt',
    'admin.show': 'Zobrazit',
    'admin.edit': 'Upravit',
    'admin.volume': 'Objem (m³)',
    'admin.price': 'Cena (CZK)',
    'admin.dimensions': 'Rozměry (m)',
    'admin.description': 'Popis',
    'admin.preset': 'Přednastavení',
    'admin.custom': 'Vlastní',
    'admin.makeVisible': 'Okamžitě zviditelnit na webu',
    'admin.cancel': 'Zrušit',
    'admin.adding': 'Přidávání...',
    'admin.addContainer': 'Přidat kontejner',
    'admin.addExcavator': 'Přidat bagr',
    'admin.excavatorImage': 'Fotografie bagru',
    'admin.model': 'Model',
    'admin.type': 'Typ',
    'admin.mini': 'Mini',
    'admin.standard': 'Standardní',
    'admin.large': 'Velký',
    'admin.specs': 'Specifikace',
    'admin.weight': 'Hmotnost',
    'admin.bucketCapacity': 'Kapacita lžíce',
    'admin.maxReach': 'Maximální dosah',
    'admin.failedUpdateStatus': 'Nepodařilo se aktualizovat stav kontejneru',
    'admin.failedDelete': 'Nepodařilo se smazat kontejner',
    'admin.failedAdd': 'Nepodařilo se přidat kontejner. Zkuste to prosím znovu.',
    'admin.fillAllDimensions': 'Prosím vyplňte všechna pole rozměrů (délka, šířka, výška)',
    'admin.confirmDelete': 'Opravdu chcete smazat {volume}m³ kontejner?',
    'admin.confirmDeleteExcavator': 'Opravdu chcete smazat {model} bagr?',
    
    // Error messages
    'error.timeSlotBooked': 'Tento časový slot je již obsazen. Prosím vyberte jiný čas.',
    'error.failedOrder': 'Nepodařilo se vytvořit objednávku',
    'error.failedBooking': 'Nepodařilo se zpracovat rezervaci',
    'error.failedFetchSlots': 'Nepodařilo se načíst dostupné termíny',
    'error.failedUpdateStatus': 'Nepodařilo se aktualizovat stav',
    'error.failedDelete': 'Nepodařilo se smazat',
    'error.failedAdd': 'Nepodařilo se přidat',
    'error.failedSave': 'Nepodařilo se uložit',
    'error.requiredFields': 'Prosím vyplňte všechna povinná pole',
    'error.somethingWrong': 'Něco se pokazilo. Zkuste to prosím znovu.',
    
    // Container options
    'order.container.3m3': '3m³ kontejner (2 x 0,5 x 3,8 m)',
    'order.container.5m3': '5m³ kontejner (2 x 0,7 x 3,8 m)',
    
    // Excavator options
    'order.excavator.tb145': 'TB145 - Mini bagr (1,5t, 0,04m³ lžíce)',
    'order.excavator.tb290-1': 'TB290-1 - Kompaktní bagr (2,9t, 0,09m³ lžíce)',
    'order.excavator.tb290-2': 'TB290-2 - Těžký bagr (2,9t, 0,11m³ lžíce)',
    
    // Construction options
    'order.construction.general': 'Obecné stavebnictví',
    'order.construction.earthworks': 'Zemní práce',
    'order.construction.foundation': 'Základové práce',
    'order.construction.demolition': 'Demolice',
    
    // Countries
    'order.country.czechRepublic': 'Česká republika',
    'order.country.slovakia': 'Slovensko',
    'order.country.germany': 'Německo',
    'order.country.poland': 'Polsko',
    'order.country.austria': 'Rakousko',
    
    // Work With Us
    'work.buttonText': 'Připojte se k našemu rostoucímu týmu!',
    'work.formTitle': 'Hledáme nové kolegy!',
    'work.subtitle': 'Aktivně rozšiřujeme náš tým a vítáme talentované odborníky, kteří s námi porostou',
    'work.firstName': 'Jméno',
    'work.lastName': 'Příjmení',
    'work.email': 'Email',
    'work.phone': 'Telefon',
    'work.expertise': 'Vaše odbornost',
    'work.experience': 'Roky zkušeností',
    'work.message': 'Řekněte nám o sobě',
    'work.submit': 'Odeslat žádost',
    'work.cancel': 'Zrušit',
    'work.sending': 'Odesílání...',
    'work.success': 'Žádost byla úspěšně odeslána!',
    'work.error': 'Nepodařilo se odeslat žádost. Zkuste to prosím znovu.',
    'work.expertise.demolition': 'Demolice',
    'work.expertise.construction': 'Stavebnictví',
    'work.expertise.operator': 'Obsluha strojů',
    'work.expertise.safety': 'Bezpečnostní specialista',
    'work.expertise.management': 'Projektový management',
    'work.expertise.other': 'Jiné',
    
    // Footer
    'footer.contact': 'Kontakt',
    'footer.followUs': 'Sledujte nás',
    'footer.socialInfo': 'Sledujte nás na sociálních sítích pro nejnovější informace',
    'footer.allRightsReserved': 'Všechna práva vyhrazena',
    'footer.privacy': 'Ochrana soukromí',
    'footer.terms': 'Obchodní podmínky',
  },
  ru: {
    // Navigation
    'nav.containers': 'Контейнеры',
    'nav.excavators': 'Экскаваторы',
    'nav.constructions': 'Строительство',
    'nav.home': 'Выберите раздел для изучения наших услуг',
    
    // Containers
    'containers.title': 'Контейнеры',
    'containers.explore': 'Изучите наши контейнерные решения',
    'containers.subtitle': 'Выберите из наших самых популярных размеров контейнеров. Разработано в соответствии с потребностями вашего проекта и быстро доставлено.',
    'containers.order': 'Заказать контейнер',
    'containers.3m3.desc': 'Компактный контейнер, подходящий для легких отходов, дерева, мелкого щебня, грунта и подобных материалов.',
    'containers.5m3.desc': 'Средний контейнер, идеальный для общих строительных отходов, материалов для ремонта и объемного мусора.',
    'containers.7m3.desc': 'Средний контейнер, идеальный для общих строительных отходов, материалов для ремонта и объемного мусора.',
    'containers.9m3.desc': 'Большой контейнер, идеальный для обширной уборки, проектов сноса и больших объемов отходов.',
    'containers.price': 'Цена от',
    'containers.loading': 'Загрузка контейнеров...',
    'containers.noAvailable': 'В настоящее время контейнеры недоступны.',
    'containers.vat': 'без НДС',
    
    // Excavators
    'excavators.title': 'Экскаваторы',
    'excavators.discover': 'Откройте для себя наши услуги экскаваторов',
    'excavators.subtitle': 'Профессиональные экскаваторы для всех ваших строительных и земляных работ. Качественное оборудование с опытными операторами.',
    'excavators.order': 'Заказать экскаватор',
    'excavators.mini': 'Мини-экскаватор',
    'excavators.standard': 'Стандартный экскаватор',
    'excavators.large': 'Большой экскаватор',
    'excavators.tb145.desc': 'Компактный и универсальный мини-экскаватор, идеальный для тесных пространств, ландшафтного дизайна и небольших строительных проектов.',
    'excavators.tb157.desc': 'Компактный мини-экскаватор, идеальный для копания, рытья траншей и легких демонтажных работ в ограниченных пространствах.',
    'excavators.tb260.desc': 'Средний экскаватор, подходящий для общих строительных работ, фундаментных работ и обработки материалов.',
    'excavators.tb285.desc': 'Средний экскаватор с увеличенным радиусом действия, идеальный для более глубоких раскопок и установки коммунальных услуг.',
    'excavators.tb2150.desc': 'Тяжелый экскаватор, предназначенный для крупномасштабных проектов, карьерных работ и крупных земляных работ.',
    'excavators.tb2150r.desc': 'Большой демонтажный экскаватор с увеличенным радиусом действия и мощностью для требовательных промышленных применений.',
    'excavators.price.hour': 'час',
    'excavators.loading': 'Загрузка экскаваторов...',
    'excavators.noAvailable': 'В настоящее время экскаваторы недоступны.',
    
    // Constructions
    'constructions.title': 'Строительство',
    'constructions.view': 'Посмотреть наши строительные проекты',
    'constructions.demolishing': 'Снос',
    'constructions.demolishing.desc': 'Профессиональные услуги по сносу и демонтажу',
    'constructions.installations': 'Установки',
    'constructions.installations.desc': 'Профессиональные установочные услуги',
    'constructions.plumbing': 'Сантехника и отопление',
    'constructions.plumbing.desc': 'Экспертные решения по сантехнике и отоплению',
    'constructions.order': 'Заказать строительство',
    
    // Demolishing page
    'demolishing.title': 'Снос и демонтажные работы',
    'demolishing.subtitle': 'Профессиональные услуги по сносу с современным оборудованием и опытной командой',
    'demolishing.types': 'Типы сноса',
    'demolishing.complete': 'Полный снос',
    'demolishing.complete.desc': 'Полный снос зданий включая фундаменты',
    'demolishing.partial': 'Частичный снос',
    'demolishing.partial.desc': 'Селективный снос конкретных частей зданий',
    'demolishing.interior': 'Внутренний снос',
    'demolishing.interior.desc': 'Удаление внутренних конструкций и отделки',
    'demolishing.concrete': 'Снос бетона',
    'demolishing.concrete.desc': 'Разрушение и удаление бетонных конструкций',
    'demolishing.industrial': 'Промышленный снос',
    'demolishing.industrial.desc': 'Демонтаж промышленных объектов и оборудования',
    'demolishing.emergency': 'Аварийный снос',
    'demolishing.emergency.desc': 'Круглосуточные аварийные услуги по сносу',
    'demolishing.features': 'Наши преимущества',
    'demolishing.safety': 'Безопасность прежде всего',
    'demolishing.safety.desc': 'Строгие протоколы безопасности и сертифицированный персонал',
    'demolishing.eco': 'Экологически чистый',
    'demolishing.eco.desc': 'Сортировка отходов и переработка материалов',
    'demolishing.equipment': 'Современное оборудование',
    'demolishing.equipment.desc': 'Новейшие машины и инструменты для сноса',
    'demolishing.order': 'Запросить расценки на снос',
    
    // Installations page
    'installations.title': 'Установки',
    'installations.subtitle': 'Профессиональные установочные услуги для вашей собственности',
    'installations.plumbing': 'Сантехника и отопление',
    'installations.plumbing.desc': 'Полный комплекс услуг по установке сантехники и отопления',
    'installations.order': 'Запросить расценки на установку',
    
    // Plumbing page
    'plumbing.title': 'Сантехника и отопление',
    'plumbing.coming': 'Скоро',
    'plumbing.desc': 'В настоящее время мы разрабатываем наши услуги по установке сантехники и отопления.',
    'plumbing.check': 'Пожалуйста, вернитесь позже для получения дополнительной информации.',
    
    // Common
    'common.back': 'Назад',
    'common.more': 'Узнать больше',
    
    // Order Form
    'order.title': 'Заказать услугу',
    'order.firstName': 'Имя',
    'order.lastName': 'Фамилия',
    'order.email': 'Email',
    'order.phone': 'Телефон',
    'order.address': 'Адрес услуги',
    'order.city': 'Город',
    'order.zip': 'Почтовый индекс',
    'order.country': 'Страна',
    'order.selectCountry': 'Выберите страну',
    'order.containerType': 'Тип контейнера',
    'order.excavatorType': 'Тип экскаватора',
    'order.constructionType': 'Тип строительства',
    'order.dateNeeded': 'Требуемая дата',
    'order.startTime': 'Время начала',
    'order.endTime': 'Время окончания',
    'order.additionalInfo': 'Дополнительная информация (необязательно)',
    'order.additionalInfoPlaceholder': 'Пожалуйста, предоставьте любые дополнительные детали о вашем заказе, особые требования или инструкции по доставке...',
    'order.addressPlaceholder': 'Введите ваш полный адрес',
    'order.endTimeError': '⚠ Время окончания должно быть после времени начала',
    'order.cancel': 'Отмена',
    'order.submit': 'Отправить заказ',
    'order.submitting': 'Отправка...',
    'order.success': 'Заказ успешно отправлен!',
    'order.successMessage': 'Мы скоро свяжемся с вами для обсуждения ваших требований.',
    'order.error': 'Не удалось отправить заказ. Пожалуйста, попробуйте еще раз.',
    
    // Admin
    'admin.login': 'admin',
    'admin.subtitle': 'Доступ к панели администратора',
    'admin.password': 'admin',
    'admin.signIn': 'Войти',
    'admin.signingIn': 'Вход в систему...',
    'admin.invalidPassword': 'Неверный пароль',
    'admin.backToWebsite': 'Вернуться на сайт',
    'admin.dashboard': 'admin',
    'admin.orders': 'Заказы',
    'admin.schedule': 'Расписание',
    'admin.logout': 'Выйти',
    'admin.status': 'Статус',
    'admin.total': 'Всего',
    'admin.pending': 'Ожидает',
    'admin.inProgress': 'В процессе',
    'admin.completed': 'Завершено',
    'admin.cancelled': 'Отменено',
    'admin.updateStatus': 'Обновить статус',
    'admin.viewDetails': 'Просмотр деталей',
    'admin.delete': 'Удалить',
    'admin.noOrdersFound': 'Заказы с выбранным фильтром не найдены.',
    'admin.loading': 'Загрузка...',
    'admin.error': 'Ошибка',
    'admin.calendar': 'Календарь',
    'admin.connected': 'Подключено',
    'admin.disconnected': 'Отключено',
    'admin.scheduled': 'Запланировано',
    'admin.all': 'Все',
    'admin.home': 'Главная',
    'admin.newContainers': 'Новые контейнеры',
    'admin.newExcavators': 'Новые экскаваторы',
    'admin.workApplications': 'Рабочие заявки',
    'admin.containerManagement': 'Управление контейнерами',
    'admin.containerManagementDesc': 'Управление контейнерами, отображаемыми на основном сайте',
    'admin.excavatorManagement': 'Управление экскаваторами',
    'admin.excavatorManagementDesc': 'Управление экскаваторами, отображаемыми на основном сайте',
    'admin.workApplicationsTitle': 'Рабочие заявки',
    'admin.workApplicationsDesc': 'Управление всеми отправленными клиентами формами',
    
    // Admin form fields
    'admin.addNewContainer': 'Добавить новый контейнер',
    'admin.addNewContainerDesc': 'Создать новую опцию контейнера',
    'admin.addNewExcavator': 'Добавить новый экскаватор',
    'admin.addNewExcavatorDesc': 'Создать новую опцию экскаватора',
    'admin.loadingContainers': 'Загрузка контейнеров...',
    'admin.loadingExcavators': 'Загрузка экскаваторов...',
    'admin.visible': 'Видимый',
    'admin.hidden': 'Скрытый',
    'admin.hide': 'Скрыть',
    'admin.show': 'Показать',
    'admin.edit': 'Редактировать',
    'admin.volume': 'Объем (м³)',
    'admin.price': 'Цена (CZK)',
    'admin.dimensions': 'Размеры (м)',
    'admin.description': 'Описание',
    'admin.preset': 'Предустановка',
    'admin.custom': 'Пользовательский',
    'admin.makeVisible': 'Сразу сделать видимым на сайте',
    'admin.cancel': 'Отмена',
    'admin.adding': 'Добавление...',
    'admin.addContainer': 'Добавить контейнер',
    'admin.addExcavator': 'Добавить экскаватор',
    'admin.excavatorImage': 'Фотография экскаватора',
    'admin.model': 'Модель',
    'admin.type': 'Тип',
    'admin.mini': 'Мини',
    'admin.standard': 'Стандартный',
    'admin.large': 'Большой',
    'admin.specs': 'Характеристики',
    'admin.weight': 'Вес',
    'admin.bucketCapacity': 'Емкость ковша',
    'admin.maxReach': 'Максимальный вылет',
    'admin.failedUpdateStatus': 'Не удалось обновить статус контейнера',
    'admin.failedDelete': 'Не удалось удалить контейнер',
    'admin.failedAdd': 'Не удалось добавить контейнер. Пожалуйста, попробуйте еще раз.',
    'admin.fillAllDimensions': 'Пожалуйста, заполните все поля размеров (длина, ширина, высота)',
    'admin.confirmDelete': 'Вы уверены, что хотите удалить {volume}м³ контейнер?',
    'admin.confirmDeleteExcavator': 'Вы уверены, что хотите удалить {model} экскаватор?',
    
    // Error messages
    'error.timeSlotBooked': 'Этот временной слот уже забронирован. Пожалуйста, выберите другое время.',
    'error.failedOrder': 'Не удалось создать заказ',
    'error.failedBooking': 'Не удалось обработать бронирование',
    'error.failedFetchSlots': 'Не удалось получить доступные слоты',
    'error.failedUpdateStatus': 'Не удалось обновить статус',
    'error.failedDelete': 'Не удалось удалить',
    'error.failedAdd': 'Не удалось добавить',
    'error.failedSave': 'Не удалось сохранить',
    'error.requiredFields': 'Пожалуйста, заполните все обязательные поля',
    'error.somethingWrong': 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
    
    // Container options
    'order.container.3m3': '3м³ контейнер (2 x 0,5 x 3,8 м)',
    'order.container.5m3': '5м³ контейнер (2 x 0,7 x 3,8 м)',
    
    // Excavator options
    'order.excavator.tb145': 'TB145 - Мини-экскаватор (1,5т, 0,04м³ ковш)',
    'order.excavator.tb290-1': 'TB290-1 - Компактный экскаватор (2,9т, 0,09м³ ковш)',
    'order.excavator.tb290-2': 'TB290-2 - Тяжелый экскаватор (2,9т, 0,11м³ ковш)',
    
    // Construction options
    'order.construction.general': 'Общее строительство',
    'order.construction.earthworks': 'Земляные работы',
    'order.construction.foundation': 'Фундаментные работы',
    'order.construction.demolition': 'Снос',
    
    // Countries
    'order.country.czechRepublic': 'Чешская Республика',
    'order.country.slovakia': 'Словакия',
    'order.country.germany': 'Германия',
    'order.country.poland': 'Польша',
    'order.country.austria': 'Австрия',
    
    // Work With Us
    'work.buttonText': 'Присоединяйтесь к нашей растущей команде!',
    'work.formTitle': 'Мы нанимаем!',
    'work.subtitle': 'Мы активно расширяем нашу команду и приглашаем талантливых специалистов расти вместе с нами',
    'work.firstName': 'Имя',
    'work.lastName': 'Фамилия',
    'work.email': 'Email',
    'work.phone': 'Телефон',
    'work.expertise': 'Ваша специализация',
    'work.experience': 'Годы опыта',
    'work.message': 'Расскажите нам о себе',
    'work.submit': 'Отправить заявку',
    'work.cancel': 'Отмена',
    'work.sending': 'Отправка...',
    'work.success': 'Заявка успешно отправлена!',
    'work.error': 'Не удалось отправить заявку. Пожалуйста, попробуйте еще раз.',
    'work.expertise.demolition': 'Снос',
    'work.expertise.construction': 'Строительство',
    'work.expertise.operator': 'Оператор техники',
    'work.expertise.safety': 'Специалист по безопасности',
    'work.expertise.management': 'Управление проектами',
    'work.expertise.other': 'Другое',
    
    // Footer
    'footer.contact': 'Контакты',
    'footer.followUs': 'Следите за нами',
    'footer.socialInfo': 'Следите за нами в социальных сетях для получения самой последней информации',
    'footer.allRightsReserved': 'Все права защищены',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('cs')

  useEffect(() => {
    // Load saved language or default to Czech
    const savedLang = localStorage.getItem('language') as Language
    if (savedLang) {
      setLanguageState(savedLang)
    } else {
      // Default to Czech language
      setLanguageState('cs')
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
